server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: notificationService
          uri: http://localhost:8084/
          predicates:
            - Path=/api/notifications/**